version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: template
      MYSQL_ROOT_PASSWORD: template
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
